export { default as posts } from './posts/Reducer'
export { default as errors } from './errors/Reducer'
export { default as modals } from './modals/Reducer'
export { default as user } from './user/Reducer'
export { default as notifications } from './notifications/Reducer'
